export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_COMMON_REQUEST = 'FETCH_ROLES_COMMON_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILD = 'FETCH_ROLES_FAILD';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';

export const FETCH_PURVIEWS_REQUEST = 'FETCH_PURVIEWS_REQUEST';
export const UPDATE_PURVIEW_REQUEST = 'UPDATE_PURVIEW_REQUEST';

