// 登录
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILD = 'LOGIN_USER_FAILD';
export const FETCH_PURVIEW_SUCCESS = 'FETCH_PURVIEW_SUCCESS';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILD = 'FETCH_USERS_FAILD';


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

export const USER_LOGOUT = 'USER_LOGOUT';
