// 获取视图详情请求，<视图面包屑名称使用>
export const VIEW_FETCH_REQUEST = 'VIEW_FETCH_REQUEST';

// 获取视图详情成功，<视图面包屑名称使用>
export const VIEW_FETCH_SUCCESS = 'VIEW_FETCH_SUCCESS';

// 通过项目ID获取工作簿列表请求
export const VIEW_WORKSHEETS_FETCH_REQUEST = 'VIEW_WORKSHEETS_FETCH_REQUEST';

// 通过项目ID获取工作簿列表成功
export const VIEW_WORKSHEETS_FETCH_SUCCESS = 'VIEW_WORKSHEETS_FETCH_SUCCESS';

// 通过工作簿ID，获取表格数据请求
export const VIEW_DASHBOARDS_REQUEST = 'VIEW_DASHBOARDS_REQUEST';

// 通过工作簿ID，获取表格数据请求成功数据处理
export const VIEW_WORKSHEET_RESULT_SUCCESS = 'VIEW_WORKSHEET_RESULT_SUCCESS';

// 工作簿列表拖动成功后，选中
export const VIEW_WORKSHEETS_DROP_ACTIVE = 'VIEW_WORKSHEETS_DROP_ACTIVE';

// 工作簿表格结果上移和下移及移除操作
export const VIEW_WORKSHEET_RESULT_MENU = 'VIEW_WORKSHEET_RESULT_MENU';

// 工作簿表格结果筛选请求
export const VIEW_DASHBOARD_REQUEST = 'VIEW_DASHBOARD_REQUEST';

// 工作簿表格结果筛选请求成功处理数据
export const VIEW_WORKSHEET_FILTER_SUCCESS = 'VIEW_WORKSHEET_FILTER_SUCCESS';

export const OUTPUT_VIEW_DATA_REQUEST = 'OUTPUT_VIEW_DATA_REQUEST';
export const OUTPUT_VIEW_DATA_SUCCESS = 'OUTPUT_VIEW_DATA_SUCCESS';
export const OUTPUT_VIEW_DATA_FAILD = 'OUTPUT_VIEW_DATA_FAILD';

export const APPEND_DASHBOARDS = 'APPEND_DASHBOARDS';
export const DELETE_DASHBOARDS = 'DELETE_DASHBOARDS';
export const CHANGE_DASHBOARDS_ORDER = 'CHANGE_DASHBOARDS_ORDER';
export const CHANGE_DASHBOARDS_FILTER = 'CHANGE_DASHBOARDS_FILTER';
export const CHANGE_DASHBOARDS_SORT = 'CHANGE_DASHBOARDS_SORT';
export const FETCH_DASHBOARDS_DETAIL = 'FETCH_DASHBOARDS_DETAIL';
export const FILL_DASHBOARDS_DETAIL = 'FILL_DASHBOARDS_DETAIL';

export const GETTER_VIEW_WORKSHEETS = 'GETTER_VIEW_WORKSHEETS';

export const SAVE_DASHBOARDS_REQUEST = 'SAVE_DASHBOARDS_REQUEST';
export const CLEAR_DASHBOARS = 'CLEAR_DASHBOARS';
