export const STATEMENT_ALL_VIEWS_REQUEST = 'STATEMENT_ALL_VIEWS_REQUEST';
export const STATEMENT_ALL_VIEWS_REQUEST_SUCCESS = 'STATEMENT_ALL_VIEWS_REQUEST_SUCCESS';

export const STATEMENT_DATA_REQUEST = 'STATEMENT_DATA_REQUEST';
export const STATEMENT_DATA_REQUEST_SUCCESS = 'STATEMENT_DATA_REQUEST_SUCCESS';

export const STATEMENT_WORKSHEET_FILTER_REQUEST = 'STATEMENT_WORKSHEET_FILTER_REQUEST';
export const STATEMENT_WORKSHEET_FILTER_REQUEST_SUCCESS = 'STATEMENT_WORKSHEET_FILTER_REQUEST_SUCCESS';

export const STATEMENT_WORKSHEET_DETAIL_REQUEST = 'STATEMENT_WORKSHEET_DETAIL_REQUEST';
export const STATEMENT_WORKSHEET_DETAIL_REQUEST_SUCCESS = 'STATEMENT_WORKSHEET_DETAIL_REQUEST_SUCCESS';

export const STATEMENT_PROJECTS_REQUEST = 'STATEMENT_PROJECTS_REQUEST';
export const STATEMENT_PROJECTS_REQUEST_SUCCESS = 'STATEMENT_PROJECTS_REQUEST_SUCCESS';

export const STATEMENT_PROJECT_VIEWS_REQUEST = 'STATEMENT_PROJECT_VIEWS_REQUEST';
export const STATEMENT_PROJECT_VIEWS_REQUEST_SUCCESS = 'STATEMENT_PROJECT_VIEWS_REQUEST_SUCCESS';

export const STATEMENT_FETCH_DASHBOARDS = 'STATEMENT_FETCH_DASHBOARDS';
export const STATEMENT_FETCH_DASHBOARDS_DETAIL = 'STATEMENT_FETCH_DASHBOARDS_DETAIL';

export const STATEMENT_OUTPUT_DASHBOARD_REQUEST = 'STATEMENT_OUTPUT_DASHBOARD_REQUEST';
export const STATEMENT_OUTPUT_DASHBOARD_FAIL = 'STATEMENT_OUTPUT_DASHBOARD_SUCCESS';
export const STATEMENT_OUTPUT_DASHBOARD_SUCCESS = 'STATEMENT_OUTPUT_DASHBOARD_SUCCESS';
