export const DRAGING_ITEM = 'DRAGING_ITEM';
export const DROP_ITEM = 'DROP_ITEM';
export const DRAGEND_ITEM = 'DRAGEND_ITEM';
export const GET_GEE_CAPTCHA = 'GET_GEE_CAPTCHA';

export const SET_DRAG_STATUS = 'SET_DRAG_STATUS';
export const SET_DRAGOVER_VALUE = 'SET_DRAGOVER_VALUE';
export const SET_DRAGHOVER_VALUE = 'SET_DRAGHOVER_VALUE';
export const REMOVE_DRAG_ITEM = 'REMOVE_DRAG_ITEM';
export const MOUSEDOWN_DRAG_ITEM = 'MOUSEDOWN_DRAG_ITEM';
export const START_DRAGING_ITEM = 'START_DRAGING_ITEM';
export const END_DRAGING_ITEM = 'END_DRAGING_ITEM';
