export const SELECT_VALUE = 'SELECT_VALUE';
export const SELECT_COLUMN = 'SELECT_COLUMN';
export const SELECT_ROW = 'SELECT_ROW';

export const ACCPET_VALUE = 'ACCPET_VALUE';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const RENAME_VALUE = 'RENAME_VALUE';

export const DRAG_VALUE_ACCPET = 'DRAG_VALUE_ACCPET';
export const DRAG_VALUE_REMOVE = 'DRAG_VALUE_REMOVE';
export const DRAG_VALUE_HOVER = 'DRAG_VALUE_HOVER';

export const FETCH_WORKSHEETS_REQUEST = 'FETCH_WORKSHEETS_REQUEST';
export const FETCH_WORKSHEETS_SUCCESS = 'FETCH_WORKSHEETS_SUCCESS';

export const FETCH_WORKSHEET_FIELDS_REQUEST = 'FETCH_WORKSHEET_FIELDS_REQUEST';
export const FETCH_WORKSHEET_FIELDS_SUCCESS = 'FETCH_WORKSHEET_FIELDS_SUCCESS';

export const SAVE_WORKSHEET_BASE = 'SAVE_WORKSHEET_BASE';
export const SAVE_WORKSHEET_BASE_SUCCESS = 'SAVE_WORKSHEET_BASE_SUCCESS';

export const SAVE_WORKSHEET_DATA_REQUEST = 'SAVE_WORKSHEET_DATA_REQUEST';
export const SAVE_WORKSHEET_DATA_SUCCESS = 'SAVE_WORKSHEET_DATA_SUCCESS';
export const SAVE_WORKSHEET_DATA_FAILD = 'SAVE_WORKSHEET_DATA_FAILD';

export const OUTPUT_WORKSHEET_DATA_REQUEST = 'OUTPUT_WORKSHEET_DATA_REQUEST';
export const OUTPUT_WORKSHEET_DATA_SUCCESS = 'OUTPUT_WORKSHEET_DATA_SUCCESS';
export const OUTPUT_WORKSHEET_DATA_FAILD = 'OUTPUT_WORKSHEET_DATA_FAILD';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILD = 'FETCH_DATA_FAILD';

export const FETCH_WORKSHEET_REQUEST = 'FETCH_WORKSHEET_REQUEST';
export const FETCH_WORKSHEET_SUCCESS = 'FETCH_WORKSHEET_SUCCESS';

export const GETTER_VIEW_DATA = 'GETTER_VIEW_DATA';

export const DRAGING_ITEM = 'DRAGING_ITEM';
export const DROP_ITEM = 'DROP_ITEM';
export const DRAGEND_ITEM = 'DRAGEND_ITEM';

export const SORT_CHANGE = 'SORT_CHANGE';

export const CHANGE_VALUE_OPTION = 'CHANGE_VALUE_OPTION';
export const FILTER_CHANGE = 'FILTER_CHANGE';
export const RESET_WORKSHEET_DATA = 'RESET_WORKSHEET_DATA';


export const GETTER_VALUE_MENU = 'GETTER_VALUE_MENU';
export const GETTER_ROW_MENU = 'GETTER_ROW_MENU';
export const GETTER_COLUMN_MENU = 'GETTER_COLUMN_MENU';
export const GETTER_DIMENSITION_MENU = 'GETTER_DIMENSITION_MENU';
export const GETTER_MEASURE_MENU = 'GETTER_MEASURE_MENU';
export const GETTER_FILTER_MENU = 'GETTER_FILTER_MENU';
export const GETTER_CALC_MATH = 'GETTER_CALC_MATH';
export const GETTER_RESULT_TYPES = 'GETTER_RESULT_TYPES';

export const ADD_CALC_FIELD = 'ADD_CALC_FIELD';
export const REMOVE_SOURCE_FIELD = 'REMOVE_SOURCE_FIELD';
export const TEST_CALC_FIELD = 'TEST_CALC_FIELD';


export const ADD_CATEGORY_FIELD = 'ADD_CATEGORY_FIELD';
export const CHANGE_CATEGORY_ORDER = 'CHANGE_CATEGORY_ORDER';
export const TOGGLE_CATEGORY_ACTIVE = 'TOGGLE_CATEGORY_ACTIVE';
export const EXPAND_CATEGORY = 'EXPAND_CATEGORY';
export const BACK_CATEGORY = 'BACK_CATEGORY';


export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const HISTORY_REVERT = 'HISTORY_REVERT';
export const HISTORY_BACK = 'HISTORY_BACK';
export const HISTORY_FORWORD = 'HISTORY_FORWORD';
export const HISTORY_UPDATE_WORKSHEET = 'HISTORY_UPDATE_WORKSHEET';
export const SET_LOCAL_WORKSHEET_STATUS = 'SET_LOCAL_WORKSHEET_STATUS';
export const LOAD_LOCAL_WORKSHEET = 'LOAD_LOCAL_WORKSHEET';
export const CLEAR_LOCAL_WORKSHEET = 'CLEAR_LOCAL_WORKSHEET';


export const SWITCH_RESULT_TYPE = 'SWITCH_RESULT_TYPE';
export const SET_WORKSHEET_TABLE_PAGE = 'SET_WORKSHEET_TABLE_PAGE';

export const WORKSHEET_PAGE_CHANGE = 'WORKSHEET_PAGE_CHANGE';
