// 数据源详情请求
export const FETCH_SOURCE_REQUEST = 'FETCH_SOURCE_REQUEST';

// 数据源详情请求成功处理
export const FETCH_SOURCE_SUCCESS = 'FETCH_SOURCE_SUCCESS';

export const FETCH_SOURCE_FAILD = 'FETCH_SOURCE_FAILD';

// 通过数据源连接获取表列表请求
export const SOURCE_TABLES_REQUEST = 'SOURCE_TABLES_REQUEST';

// 通过数据源连接获取表列表请求数据处理
export const SOURCE_TABLES_SUCCESS = 'SOURCE_TABLES_SUCCESS';

// 通过表，获取字段请求
export const SOURCE_TABLES_FIELDS_REQUEST = 'SOURCE_TABLES_FIELDS_REQUEST';

// 通过表，获取字段请求成功数据处理
export const SOURCE_TABLES_FIELDS_SUCCESS = 'SOURCE_TABLES_FIELDS_SUCCESS';

// 度量和维度相互拖动
export const SOURCE_RESULT_DROP_REQUEST = 'SOURCE_RESULT_DROP_REQUEST';

// 维度删除操作
export const SOURCE_DIMENSION_REMOVE_REQUEST = 'SOURCE_DIMENSION_REMOVE_REQUEST';

// 度量删除操作
export const SOURCE_MEASURE_REMOVE_REQUEST = 'SOURCE_MEASURE_REMOVE_REQUEST';

// 度量和维度重命名
export const SOURCE_RESULT_RENAME_REQUEST = 'SOURCE_RESULT_RENAME_REQUEST';

// 初始化上次保存的数据字段请求
export const SOURCE_INIT_FIELDS_REQUEST = 'SOURCE_INIT_FIELDS_REQUEST';

// 初始化上次保存的数据处理
export const SOURCE_INIT_FIELDS_SUCCESS = 'SOURCE_INIT_FIELDS_SUCCESS';

// 选择表，维度和度量集合重置
export const SOURCE_FIELDS_RESET_REQUEST = 'SOURCE_FIELDS_RESET_REQUEST';

export const FETCH_SOURCE_DATA_PURVIEW = 'FETCH_SOURCE_DATA_PURVIEW';

export const SAVE_SOURCE_REQUEST = 'SAVE_SOURCE_REQUEST';
