export const FETCH_DATABASES_REQUEST = 'FETCH_DATABASES_REQUEST';
export const FETCH_DATABASES_SUCCESS = 'FETCH_DATABASES_SUCCESS';
export const DELETE_DATABASE_REQUEST = 'DELETE_DATABASE_REQUEST';

export const FETCH_DATABASE_REQUEST = 'FETCH_DATABASE_REQUEST';

export const FETCH_DATABASES_ROLE_REQUEST = 'FETCH_DATABASES_ROLE_REQUEST';
export const FETCH_SCHEMES_REQUEST = 'FETCH_SCHEMES_REQUEST';
export const FETCH_TABLES_REQUEST = 'FETCH_TABLES_REQUEST';
export const FETCH_COLUMNS_REQUEST = 'FETCH_COLUMNS_REQUEST';

export const APPEND_SOURCE_TABLE = 'APPEND_SOURCE_TABLE';
export const REMOVE_SOURCE_TABLE = 'REMOVE_SOURCE_TABLE';

export const MOVE_MOUSE_SOURCE = 'MOVE_MOUSE_SOURCE';

export const START_TABLE_RELATION = 'START_TABLE_RELATION';
export const START_TABLE_MOVE = 'START_TABLE_MOVE';
export const ADD_TABLE_RELATION = 'ADD_TABLE_RELATION';
export const END_TABLE_RELATION = 'END_TABLE_RELATION';
export const DELETE_TABLE_RELATION = 'DELETE_TABLE_RELATION';
export const END_TABLE_MOVE = 'END_TABLE_MOVE';

export const RESET_DATABASE_TABLES = 'RESET_DATABASE_TABLES';
export const INIT_DATABASE_TABLES = 'INIT_DATABASE_TABLES';

export const FETCH_DATABASE_FILTER = 'FETCH_DATABASE_FILTER';
export const DELETE_DATABASE_FILTER = 'DELETE_DATABASE_FILTER';
export const SAVE_DATABASE_FILTER = 'SAVE_DATABASE_FILTER';

export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';
export const CHANGE_VIEW_SQL = 'CHANGE_VIEW_SQL';

