export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';

export const FETCH_SOURCES_REQUEST = 'FETCH_SOURCES_REQUEST';
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';

export const FETCH_VIEWS_REQUEST = 'FETCH_VIEWS_REQUEST';
export const FETCH_VIEWS_SUCCESS = 'FETCH_VIEWS_SUCCESS';

export const LOAD_PROHECT_INFO = 'LOAD_PROHECT_INFO';
